apiVersion: 1

datasources:
  - name: MySQL
    type: mysql
    url: "${DB_URL}:${DB_PORT}"
    database: "certsuite_usage_db"
    user: "${DB_USER}"
    secureJsonData:
      password: "${DB_PASSWORD}"
    jsonData:
      tlsAuth: false
      tlsAuthWithCACert: false
      